-- Calls table
CREATE TABLE `Calls` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `callerID` INT UNSIGNED NOT NULL,
    `receiverID` INT UNSIGNED NOT NULL,
    `call_start` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `call_end` TIMESTAMP NULL,
    `duration` INT UNSIGNED,
    `call_status` VARCHAR(255),
    FOREIGN KEY (`callerID`) REFERENCES Users(`ID`) ON DELETE CASCADE,
    FOREIGN KEY (`receiverID`) REFERENCES Users(`ID`) ON DELETE CASCADE
);