
-- Sessions table
CREATE TABLE `Sessions` (
    `UUID` VARCHAR(255) NOT NULL PRIMARY KEY,
    `userID` INT UNSIGNED NOT NULL,
    `token` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `expires_at` TIMESTAMP NOT NULL,
    FOREIGN KEY (`userID`) REFERENCES Users(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);

